### PR TITLE
adds VictoriaMetrics Cloud to the list of Status pages

### PR DESCRIPTION
**Pull request by denisgolius**
This PR will add https://status.victoriametrics.com to `common/status_pages/status_pagees.go`.

### CODE REVIEW

**Comment by Chrisbattarbee** [comment]
Hey @denisgolius! Thanks for the PR, could you remove the trailing slash? I'll add some more defensive parsing in a few hours but for the parsing to work at the moment the trailing slash should be removed

**Comment by denisgolius** [comment]
> Hey @denisgolius! Thanks for the PR, could you remove the trailing slash? I'll add some more defensive parsing in a few hours but for the parsing to work at the moment the trailing slash should be removed

Hello @Chrisbattarbee 
Done :)

**Comment by Chrisbattarbee** [comment]
Thank you!

**Comment by Chrisbattarbee** [comment]
image

**Pull request merged**
